sensor:
  - platform: openweathermap
    api_key: !secret openweathermap_api
    language: es
    monitored_conditions:
      - weather
      - temperature
      - wind_speed
      - wind_bearing
      - humidity
      - pressure
      - clouds
      - rain
      - snow
      - weather_code