sensor:
  - platform: reddit
    username: !secret reddit_user
    password: !secret reddit_pass
    client_id: !secret reddit_id
    client_secret: !secret reddit_secret
    subreddits:
      - news
      - worldnews
    sort_by: hot
