title: Home
views:

  - path: general
    title: General
    theme: google_dark_theme
    badges:
      -  person.alejandro
    cards:
      - type: map
        dark_mode: true
        state_color: true
        default_zoom: 12
        entities:
          - zone.home
          - device_tracker.pixel_2_xl
      - type: weather-forecast
        entity: weather.casa
      - type: picture-elements
        state_color: true
        dark_mode: true
        image: 'http://homeassistant:8123/local/plano.png'
        elements:
          - entity: sensor.hp_envy_5000_series
            navigation_path: /lovelace/oficina
            prefix: HP ENVY 5010
            icon: mdi:printer
            style:
              font-size: 8px
              left: 75%
              top: 80%
            type: state-badge
          - entity: media_player.altavoces_cuarto
            navigation_path: /lovelace/multimedia
            prefix: Google Home Mini
            style:
              font-size: 8px
              left: 85%
              top: 80%
            type: state-badge
          - entity: media_player.plex_plexamp_desktop
            navigation_path: /lovelace/multimedia
            prefix: Plexamp DESKTOP
            style:
              font-size: 8px
              left: 92%
              top: 80%
            type: state-badge
          - entity: media_player.salon_moderno
            navigation_path: /lovelace/multimedia
            prefix: Google Chromecast 
            style:
              font-size: 8px
              left: 24%
              top: 40%
            type: state-badge
          - entity: sensor.pi_hole_seen_clients
            navigation_path: /lovelace/seguridad
            prefix: Pi-Hole
            style:
              font-size: 8px
              left: 20%
              top: 12%
            type: state-badge
          - entity: sensor.cpu_load_15_min
            navigation_path: /lovelace/multimedia
            prefix: CPU NAS
            style:
              font-size: 8px
              left: 40%
              top: 40%
            type: state-badge

  - path: tiempo
    title: Tiempo & Temperaturas
    theme: google_dark_theme
    badges:
    cards:
      - type: iframe
        aspect_ratio: 100%
        url: https://embed.windy.com/
      - type: glance
        title: OpenWeatherMap
        state_color: true
        columns: 2
        entities:
          - entity: sensor.owm_condition
            name: Condición
          - entity: sensor.owm_temperature
            name: Temperatura
          - entity: sensor.owm_wind_speed
            name: Velocidad viento
            icon: mdi:weather-windy
          - entity: sensor.owm_cloud_coverage
            name: Cobertura nubes
            icon: mdi:cloud
          - entity: sensor.owm_humidity
            name: Humedad
            icon: mdi:water-percent
          - entity: sensor.owm_pressure
            name: Presión atmosférica
            icon: mdi:weather-windy-variant
          - entity: sensor.owm_rain
            name: Lluvia
            icon: mdi:weather-pouring
          - entity: sensor.owm_snow
            name: Nieve
            icon: mdi:grain
          - entity: sensor.owm_weather_code
            name: Código OWM
            icon: mdi:barcode
          - entity: sensor.owm_wind_bearing
            name: Dirección viento
            icon: mdi:angle-acute
      - type: button
        entity: switch.sonoff
        name: Enchufe Dormitorio
        show_name: true
        show_icon: true
        state_color: true

  - path: multimedia
    title: Multimedia
    theme: google_dark_theme
    badges:
      - binary_sensor.minecraft_server_status
      - sensor.minecraft_server_players_online
      - sensor.minecraft_server_latency_time
      - sensor.fertry
      - sensor.steam
      - sensor.steam_game
      - sensor.minecraft_version
    cards:
      - type: media-control
        name: Chromecast Salón
        entity: media_player.salon_moderno
      - type: media-control
        name: Altavoces Dormitorio
        entity: media_player.altavoces_cuarto 
      - type: media-control
        name: Plexamp Desktop
        entity: media_player.plex_plexamp_desktop 
      - type: media-control
        name: Spotify
        entity: media_player.spotify
      - type: media-control
        name: Plex Web
        entity: media_player.plex_plex_web_chrome
      - type: entity
        name: Plex Desktop
        entity: sensor.plex_fertry_desktop

  - path: seguridad
    title: Seguridad
    theme: google_dark_theme
    badges:
      - sensor.gdacs
    cards:
      - type: sensor
        entity: sensor.pi_hole_ads_percentage_blocked_today
        name: '% anuncios bloqueados'
      - type: glance
        columns: 2
        show_state: true
        state_color: true
        title: Pi-Hole
        entities:
          - entity: sensor.pi_hole_ads_blocked_today
            name: Bloqueados hoy
            show_state: true
          - entity: sensor.pi_hole_dns_queries_cached
            name: En caché
            show_state: true
          - entity: sensor.pi_hole_dns_queries_forwarded
            name: Aceptados
            show_state: true
          - entity: sensor.pi_hole_dns_queries_today
            name: Peticiones
            show_state: true
          - entity: sensor.pi_hole_dns_unique_domains
            name: Dominios
            show_state: true
          - entity: sensor.pi_hole_domains_blocked
            name: Dominios bloqueados
            show_state: true
      - type: alarm-panel
        entity: alarm_control_panel.gateway_alarm 
        name: Alarma
        states:
          - arm_home
          - arm_away

  - path: oficina
    title: Oficina
    theme: google_dark_theme
    badges:
      - binary_sensor.fertry_tech
      - sensor.pi_hole_seen_clients
      - sensor.hacs
      - sensor.speedtest_download
      - sensor.speedtest_ping
      - sensor.speedtest_upload
    cards:
      - type: sensor
        entity: sensor.cpu_load_15_min
        name: NAS CPU Load
      - type: glance
        columns: 2
        show_state: true
        state_color: true
        title: NAS Synology DSM
        entities:
          - entity: sensor.network_down
            name: Velocidad Descarga
            show_state: true
          - entity: sensor.network_up
            name: Velocidad Subida
            show_state: true
          - entity: sensor.drive_1_temperature
            name: Temperatura Disco 1
            show_state: true
          - entity: sensor.drive_2_temperature
            name: Temperatura Disco 2
            show_state: true
          - entity: sensor.memory_available_real
            name: Memoria
            show_state: true
          - entity: sensor.memory_total_swap
            name: Intercambio
            show_state: true
      - type: entities
        title: HP Envy 5010
        state_color: true
        entities:
          - entity: sensor.hp_envy_5000_series
            name: Estado
          - entity: sensor.hp_envy_5000_series_black_ink 
            name: Tinta negra
          - entity: sensor.hp_envy_5000_series_tri_color_ink 
            name: Tinta color

  - path: otros
    title: Otros
    theme: google_dark_theme
    badges:
      - sensor.pixel_2_xl_battery_level 
    cards:
      - type: history-graph
        title: Bitcoin
        entities:
          - entity: sensor.bitcoin
            name: Bitcoin current
      - type: sensor
        name: Precio Voluntario Pequeño Consumidor (PVPC)
        entity: sensor.pvpc
      - type: entity
        entity: sensor.pixel_2_xl_geocoded_location
        name: Localización 
      - type: entity
        entity: sensor.pixel_2_xl_wifi_connection
        name: Conexión actual 
      - type: entity
        entity: sensor.pixel_2_xl_battery_state
        name: Estado batería 
    